# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 382540dca74b407f17ac63c01a36fe8bcc7442e06e0891d091e81d011ec870ff5e09bfd5d412cb3d9f5c30a6c61dc98dd165be8878e4000af5a8210cd0024e7d

test:
  secret_key_base: ce5c1ae7e19afea9f49c3022e27673a5cd446e3419eb698f721601c5a6fad02c4d24905457cd9a44e80a1c0cdb9453b9d6c5cf9402f0d54a09326449e1083fe2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
